development:
  adapter:   postgresql
  database:  'ilias-sidekiq-deis-app'
  username:  'deploy'
  password:  'OPs8KBt1oH'
  host:      'ec2-18-191-70-190.us-east-2.compute.amazonaws.com'
  reconnect: true